### ISSUE TITLE
Trace agent doesn't create new trace id for each request

### ISSUE THREAD

**Issue by vtajzich** [googleapis/nodejs-logging-winston#287]
**Issue**

Log entries are not assigned to specific requests when application is under load.
Value of trace field is same for all log lines but it should be unique.

**Environment**

NodeJS, Express, Typescript

example project: https://github.com/vtajzich/nodejs-gcp-trace-agent-test

**Steps to reproduce**

1. Set environment variables LOGGING_PROJECT_ID and SA_LOGGING_FILE (absolute path to json with private key to access logging and tracing)
1. Run the application
1. Run multiple concurrent requests (using jMeter or similar tool)
1. Go to trace list and observe requests

**Current**

- All log entries are assigned to the first request ![](https://github.com/vtajzich/nodejs-gcp-trace-agent-test/blob/master/log_entries_assigned_to_first_request.png?raw=true)
- Other requests have no logs at all ![](https://github.com/vtajzich/nodejs-gcp-trace-agent-test/blob/master/no_log_lines.png?raw=true)
- trace id (field "trace") is same for all log lines

**Expected**

- Each request has assigned log lines which belongs to it
- trace id is unique for each request

**Comment by DominicKramer** [comment]
@kjin thanks for moving this issue here.  @soldair since you implemented the Winston 3 functionality, would you mind working on this issue?

**Comment by DominicKramer** [comment]
@kjin Sorry, I didn't see that you are still working on this.  I talked with @soldair, and they will let you work on this.

**Comment by kjin** [comment]
@vtajzich After looking deeper into this for the last few days, it seems definite that a long-term fix would require that we ask for changes in either `winston` or other third-party modules, as we can't automatically obtain the correct trace ID given the way winston@3 is implemented right now.

In the meantime, it is a bit clunky, but you can work around this by setting a metadata field on your logs at the time the log is called:

```
// Instead of...
logger.info('a log message');
// Try...
const tracer = require('@google-cloud/trace-agent').start(/**/);
const { LOGGING_TRACE_KEY } = require('@google-cloud/logging-winston');
logger.info('a log message', { [LOGGING_TRACE_KEY]: `projects/${agent.getWriterProjectId()}/traces/${agent.getCurrentContextId()}` });
```

**Comment by vtajzich** [comment]
@kjin Why it is blocked? 

This is show stopper for us. It would cost us lot of energy to change logging in this way or to write some kind of wrapper to provide this functionality.

This is fundamental feature in order to be able use stackdriver & tracing in GCP.

**Comment by kjin** [comment]
Sorry, I should have updated this thread to note that we made a feature request https://github.com/winstonjs/winston/issues/1626 to see if we can get the minimum behavior needed to support a better solution. Until then monkeypatching the logger object to automatically inject metadata would be the only other way.

**Comment by kjin** [comment]
@vtajzich Thanks for the update, what do you mean by "logs are assigned to the very first event"? Would you be able to share a screenshot?

We've discussed this some more and it seems like the Winston issue linked above isn't explicitly blocking a different, possibly more functional workaround.

Winston 3 config has a field `defaultMeta` that accepts an object that will be copied as metadata for each request. They use `Object.assign` to copy the object, which means we can supply an object with getters for each field -- these getters will get invoked upon `Object.assign`. So you could try supplying the object exported by this file: https://gist.github.com/kjin/8e07710b0684f5b4c9416bdc45b37fb6

This doesn't change the way the trace ID is getting generated, it only does what I suggested earlier about setting metadata, but automatically.

If this works for you we'll likely make it part of this library itself. It's true that now you have to set `transports` and `defaultMeta`, but I believe this is the only way to have logging-trace correlation work in Winston 3.

BTW, as part of this issue I realized that timestamps are also being set too late, which causes rendering issues in the UI later, so you might be seeing something like this:
![image](https://user-images.githubusercontent.com/2365820/55824210-420ad800-5ab8-11e9-85e6-bb158125e4dc.png)

With the file linked above, as well as a fix I opened in #294, it should look like this, which is more accurate:
![image](https://user-images.githubusercontent.com/2365820/55824272-68307800-5ab8-11e9-865f-64f57acd9538.png)

**Comment by vtajzich** [comment]
I've updated the example (added numbers to log messages to be able follow them in order).

Take a look on screenshots, logs are not ordered properly and they are not assigned to proper segment (log line 1 and 5 should be assigned to HTTP request, log lines 2-4 to nested level).

Very first request:
![](https://github.com/vtajzich/nodejs-gcp-trace-agent-test/blob/master/default_meta_request-1.png?raw=true)

Second request in batch:
![](https://github.com/vtajzich/nodejs-gcp-trace-agent-test/blob/master/default_meta_request-2.png?raw=true)

**Comment by kjin** [comment]
I believe the Stackdriver UI doesn't necessarily nest logs, but places them on the timeline based on their timestamp. So in your first screenshot, rather than (1) being nested under the root span, it happens to have a timestamp that is very close to the beginning of the request (which is expected). The problem you're seeing is that the other logs are assigned slightly inaccurate timestamps (also due to the same problem from Winston that it buffers logs before passing them to transports). I added the ability to read timestamps from metadata in #294 and expect that it be released in 0.11.1 imminently (probably today).

See my second screenshot above, which is the result of using the `default-meta.js` I provided, in addition to the fix from #294. The logs are placed correctly on the timeline; as you would expect, the first two logs (1) and (2) are emitted right before the request to `www.googleapis.com` is made, and the subsequent logs (3), (4), and (5) are emitted some time after you get the response, and immediately before your server sends its response. I'm not sure if it would make sense for logs 3-5 to appear under the `www.googleapis.com` span because they aren't even logged until after that request is finished.

**Comment by vtajzich** [comment]
Version 0.11.1 together with default meta works well. There is only one issue i can spot right now - ordering of the log lines in trace UI. Otherwise it looks pretty good. 

@kjin good work!

**Comment by kjin** [comment]
Hi @vtajzich, great to hear that. Logs appearing out of order is a UI bug -- as it appears to happen when logs with the same timestamp are rendered and it only affects the Trace UI and not the Logging UI. I've filed an internal issue requesting that fix.

I'll keep this issue open to track work on getting the functionality for assigning `defaultMeta` into this module.

**Comment by daaain** [comment]
I have run into this problem too unfortunately 😿 the fix in the linked Gist doesn't work either, can't seem to get hold of the global variable of the trace agent – maybe because we're using Typescript transpilation and `import` instead of `require`?

However I realised something, since all our requests come through GKE ingress load balancer, there should already be an `X-Cloud-Trace-Context` header generated: https://cloud.google.com/load-balancing/docs/https/#components

So wondering what would be the simplest way to reuse these with the middleware? Or maybe it doesn't even make sense to use the middleware in this case? If so, is there a way to set the `trace` property on a log entry manually?

**Comment by kjin** [comment]
> I have run into this problem too unfortunately 😿 the fix in the linked Gist doesn't work either, can't seem to get hold of the global variable of the trace agent – maybe because we're using Typescript transpilation and `import` instead of `require`?

The global variable should be synchronously set after calling `require('@google-cloud/trace-agent').start()`. It may be true that TypeScript is re-ordering your `import` -> `require` statements during transpilation.

You can also use, in lieu of `global._google_trace_agent`, `require('@google-cloud/trace-agent').get()` to get a guaranteed non-null reference to the Trace Agent. This returns the same value as `start()`, regardless of whether it was called before or after. (If called before `start()`, it will be disabled until `start()` is called). (The reason I didn't include it in the snippet was because I was intending to eventually introduce the code into this project, where we wouldn't want an explicit require of the Trace Agent)

**Comment by daaain** [comment]
Thanks a lot for the help @kjin!

In the end I figured out how to work with the existing trace id coming in via the Google API gateway header which is much simpler:

```js
// extract trace key from header added by Google API gateway to pass to request handling
const trace = get(req, 'headers.x-cloud-trace-context', null)
if (trace) {
  req.log = logger.child({
    [LoggingWinston.LOGGING_TRACE_KEY]: `projects/${
      process.env.GOOGLE_PROJECT_ID
    }/traces/${trace.match(/^([a-zA-Z0-9]*)/)[0]}`,
  })
  // let's pass it on so the client can also use the trace in its error reports
  res.set(
    'x-cloud-trace-context',
    get(req, 'headers.x-cloud-trace-context'),
  )
} else {
  req.log = logger
}
```
