### ISSUE TITLE
The README is about logging rather than logging-winston

### ISSUE THREAD

**Issue by ofrobots** [googleapis/nodejs-logging-winston#3]
The README file after the migration seems to be about the main logging library rather than logging-winston. The main inline sample is irrelevant as well.

What happened with the old README?

/cc @lukesneeringer

**Comment by gaofanmichael** [comment]
I guess it is modified by cloud-repo-tools.
In the configuration .cloud-repo-tools.json, the value for 'product' is 'logging'. So it generates all README corresponding to logging rather than logging winston. However, changing the 'product' to 'logging winston' does not work for now as there is no product named 'logging winston'. cloud-repo-tools will return with errors if we set it to 'logging winston'

**Comment by gaofanmichael** [comment]
It is now fixed. Closed for now.
https://github.com/googleapis/nodejs-logging-winston/pull/5
