### ISSUE TITLE
Should the middleware example use async functions

### ISSUE THREAD

**Issue by ofrobots** [googleapis/nodejs-logging-winston#355]
Split from https://github.com/googleapis/nodejs-logging-winston/issues/303.

@daaain:
> @ofrobots I completely understand the library's internal init being async, my beef was using the async function in user code as in the code example in the readme.

> As you can see in the code examples I posted above it's completely possible to not have an async function, but work with the promise. But ideally this should be something the library does for me.

>The main issue with doing it this sync way is that the logger instance is undefined until the async middleware init returns its own, so that's why I create a Console only Winston instance and replace it with the middleware's one once it's ready.

>Not only does this solve the async problem, but makes the logger importable anywhere in the source code without having to wait for the async function to return the instance everywhere in the codebase which would be horrendous.

**Comment by daaain** [comment]
I added some more code examples on desired middleware initialisation in the previous issue which are revelant here too I guess: https://github.com/googleapis/nodejs-logging-winston/issues/303#issuecomment-507630196

But as well as the logger instance being undefined while waiting for the async function, the big issue with the current example is that the booting up of the Express server is pushed back by however long it takes for the middleware to finish bootstrapping, and since the `await` bit is not wrapped in `try / catch` in case there's an error the server just won't start 🙀

**Comment by DominicKramer** [comment]
@ofrobots can you triage this issue since you have the most insight into its priority and potential solution?

**Comment by daaain** [comment]
The changes in #364 are great, but the code example is still using async function.

Maybe it's only me, but I still think that handling the middleware bootstrap as a (retryable) Promise outside of the Express setup is much safer. Even with the new example, if it's used as is, any error in the `await` block will crash the whole server. Not only that, but when I tried Nodemon didn't work with the async startup function (it probably thought that the process just finished), so it's going to give people a pretty bad starting experience. It did for me...

**Comment by jacobg** [comment]
It seems that this async approach doesn't work with Cloud Functions requirement to export the express app from the module, unless the developer adds a bunch of code to swap in the middleware after the promise completes. Can't this be made easier?
