### ISSUE TITLE
No GKE resource information in logs

### ISSUE THREAD

**Issue by ianwalter** [googleapis/nodejs-logging-winston#386]
Running a Node.js API on GKE and the logs are showing up in StackDriver but the resource data is empty (unlike when the API was just logging to stdout):

```js
resource: {
  labels: {
   cluster_name: "api"    
   container_name: ""    
   instance_id: ""    
   namespace_id: "default"    
   pod_id: ""    
   project_id: "myorg-001"    
   zone: ""    
  }
  type: "container"   
 }
```

#### Environment details

  - Docker image: node:12.9-slim
  - Node.js version: 12.9
  - npm version: 6.10.2
  - `@google-cloud/logging-winston` version: 2.0.1
  - GKE master version: 1.12.7-gke.25

#### Logger code

```js
const winston = require('winston');
const {LoggingWinston} = require('@google-cloud/logging-winston');

const logger = winston.createLogger({
  level: process.env.LOG_LEVEL || 'debug',
  format: winston.format.timestamp(),
  transports: [
    process.env.NODE_ENV === 'production'
      ? new LoggingWinston()
      : new winston.transports.Console({
        handleExceptions: true,
        format: winston.format.combine(
          winston.format.colorize(),
          winston.format.simple()
        ),
      }),
  ],
  exitOnError: false,
});

module.exports = logger;
```

The pod is running on the default namespace and using the default service account. How does this library identify the resource?

**Comment by bcoe** [comment]
related: https://github.com/googleapis/nodejs-logging-bunyan/issues/347; discussing this with my peer @soldair, I think we need to add some samples and tests for our logging libraries in different runtime environments.

**Comment by vcorr** [comment]
Same problem here. It makes this quite hard to use, when you can't drill into the logs with
"Kubernetes container" -> cluster name -> namespace -> container name

**Comment by genevieve314** [comment]
I am experiencing the same issue. Does any one know of a good work around?

**Comment by bcoe** [comment]
@genevieve314 you could potentially populate some of this information yourself when initializing the logger I believe, perhaps by setting the field `defaultMeta`, see:

https://github.com/winstonjs/winston#usage

We're continuing to discuss this issue internally, but I don't have any timelines, with regards to when we might populate additional information in logs.

**Comment by genevieve314** [comment]
thanks @bcoe that is what I ended up doing :)

**Comment by mlarcher** [comment]
@genevieve314 could you elaborate on the workaround you ended up doing please ? Where did you get the instance info from ?

Also, wouldn't it be possible to have the module expose the formatted logs through the console instead of a log file ? This way we could have the formatting *and* the required contextual info in the log viewer.

**Comment by soldair** [comment]
@mlarcher you have to manually provide the metadata you're interested in.
we can't because environments don't make it uniformly available.
https://github.com/winstonjs/winston#usage

here are more details about the issue pulling metadata like region in the context of cloud functions.
https://github.com/googleapis/nodejs-logging-bunyan/issues/291#issuecomment-526758642

But as the implementer of the function/container  you can provide the information you feel is important to organize your logs via the environment in your own way.

When you log to stdout the cloud platform has access to data they don't make available via other apis. if stdout logging works for you that's great! its just very difficult to get custom logging to merge into stdout logging streams.
https://github.com/googleapis/nodejs-logging-winston/issues/393

**Comment by mlarcher** [comment]
@soldair : what I get from the module is fine, it formats the data properly (severity, error objects, message, metadata...) for ingestion by stackdriver, I just wish I could get that formatted data and expose it through stdout so that gcp adds the other relevant metadata, instead of being stick with a file output that implied restricted metadata.
I totally agree that the logging library shouldn't have to handle the environments btw.

**Comment by jasperkuperus** [comment]
@bcoe What's the status on this? These missing resource labels are a showstopper for me personally.

Furthermore, I agree with @mlarcher.

**Comment by jasperkuperus** [comment]
If you're logging in JSON format and you want Stackdriver to correctly pick up severity from your logs, you can just add `severity` to your log. [This gist](https://gist.github.com/jasperkuperus/9df894041e3d5216ce25af03d38ec3f1) provides a working example.

Google provides [an overview of available log levels in Stackdriver](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#logseverity).

**Comment by sflanker** [comment]
There is no point in having a plugin if the recommendation is just going to be to log to stdout anyway.

Although it is nice to have a temporary workaround, so thanks for that @jasperkuperus. I just hope this isn't seen as a real solution.

**Comment by sflanker** [comment]
The best workaround I have found is to manually set the resource when creating the `LoggingWinston` transport:

```
new LoggingWinston({
  projectId: process.env.GCLOUD_PROJECT,
  resource: {
    type: 'k8s_container',
    labels: {
      // Get this from the "metadata.name" field in your deployment: https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/
      pod_name: process.env.POD_NAME,
      container_name: '<YOUR_DEPLOYMENT_NAME>',
      // This can also be got via a the "metadata.namespace" field in your deployment
      namespace: process.env.K8S_NAMESPACE,
      // Get this when you launch your container using curl: https://github.com/kubernetes/kubernetes/issues/44954#issuecomment-313517402
      cluster_name: config.get('K8S_CLUSTER')
    }
  }
}
```

**Comment by ezk84** [comment]
I'm with @mlarcher on this: it would be nice if this library could expose a Winston Formatter that would just give us the right JSON structure for Stackdriver.

We could then have the freedom to define the transport used: we could log that json to the console instead of to LoggingWinston and in GKE the extra metadata will be added by GCP.

**Comment by mlarcher** [comment]
iterating on the gist from @jasperkuperus we have now a setup that preserves errors in the output and uses the correct log severity for GCP. This is way closer to what we need, even though it doesn't use the nodejs-logging-winston module at all.
I'm sharing it here in case in helps someone :
```js
const winston = require('winston');
const { LEVEL } = require('triple-beam');

function preserveErrors(input) {
  const output = {};
  Object.entries(input).forEach(([key, value]) => {
    let outputValue = value;
    if (value instanceof Error) {
      outputValue = {};
      Object.getOwnPropertyNames(value).forEach((errorKey) => {
        outputValue[errorKey] = value[errorKey];
      }, this);
    }
    if (Object.prototype.toString.call(value) === '[object Object]') {
      outputValue = preserveErrors(value);
    }

    output[key] = outputValue;
  });
  return output;
}

const SeverityLookup = {
    default: 'DEFAULT',
    silly: 'DEFAULT',
    verbose: 'DEBUG',
    debug: 'DEBUG',
    http: 'notice',
    info: 'info',
    warn: 'WARNING',
    error: 'ERROR',
  };

  // add severity level for GCP stackdriver
  const stackdriverSeverityFormat = format((info) => ({
    ...info,
    severity: SeverityLookup[info[LEVEL]] || SeverityLookup.default,
  }));

  const errorsPreserverFormat = format((info) => {
    // we spread the original `info` too in order to preserve the keys behind Symbols (i.e. splat/level)
    return {
      ...info,
      ...preserveErrors(info),
    };
  });

  const formatters = [format.timestamp(), stackdriverSeverityFormat(), errorsPreserverFormat(), format.json()];

  const loggingWinston = new transports.Console({
    format: format.combine(...formatters),
    stderrLevels: ['error'],
  });
```

**Comment by synsteve** [comment]
Hi,
Has there been any further though on this issue?  I was playing with logging-winston because I want to set the trace property of the LogEntry.  However, I really want the GKE resource info to be properly populated.

**Comment by synsteve** [comment]
I've found a way to collect the info I need, but I can't populate the "resource" portion of the log entry as the call to the Log.write method is made with the callback instead of the WriteOptions.

Is there anyway I can override the resource portion of the log entry?

**Comment by synsteve** [comment]
Ah- found that you can add the resource to the options when instantiating LoggingWinston.  All working now!

**Comment by nicoleczhu** [comment]
This works now. see pr above
