### ISSUE TITLE
Custom labels overwritten by Node Labels when deploying using Kubernetes

### ISSUE THREAD

**Issue by jakexconniff** [googleapis/nodejs-logging-winston#446]
#### Environment details

  - OS: MacOS Catalina / Carbon Stretch on GKE
  - Node.js version: 8.15.1
  - npm version: 6.4.1
  - `@google-cloud/logging-winston` version: 3.0.5

#### Steps to reproduce

1. Create a logger
```  
const labelObject = { label: 'test' };
const loggingWinston = new LoggingWinston({
    labels: labelObject,
    prefix: 'prefix',
    projectId: 'project',
    keyFilename: './credentials.json'
  });
  const logger = await winston.createLogger({ level: 'info', transports: [ new winston.transports.Console(), loggingWinston ] });
```
2. Use logger.info as expected.
3. View logs in StackDriver, and see that each log item includes labels ( label: test) as expected.
4. Build Docker image (off of carbon-stretch), push to gcr.io, and then re-deploy our application on Kubernetes.
5. Look at logs and notice that that labels have been replaced by the Kubernetes node default labels:

  compute.googleapis.com/resource_name: "node-name"   
  container.googleapis.com/namespace_name: "default"   
  container.googleapis.com/pod_name: "pod-name"   
  container.googleapis.com/stream: "stdout" 

Is this intended behavior or is there already a built-in way to avoid labels being overwritten? I need some way to attach more info to my logs in order to make StackDriver useful.

**Comment by soldair** [comment]
This example cause duplicate logs to appear in the logs viewer. One set from the LoggingWinston stream, and one stdout set for the  `new winston.transports.Console()`

based on 
```
container.googleapis.com/stream: "stdout"
```
it seems like the stdout logs have their labels changed.

Do the custom logs also have their labels changed? This would help me narrow down the behavior because I'm unfamiliar with anything that might auto populate k8s vars in logs.

**Comment by jakexconniff** [comment]
Interesting, that might be what is confusing me. I do not see duplicate logs, so perhaps it would be that the second set (With my labels) is not being sent to Stackdriver properly in the first place.

Are there any common pitfalls that I can watch out for that may be preventing my second set from hitting Stackdriver? Maybe anywhere I can go to check for error messages that would guide me as well. 

Otherwise this should be able to be closed and I can investigate more, then update this for posterity when I find a solution.

**Comment by soldair** [comment]
it may be hard to find exactly which section the logs appear under in the UI but they should be there somewhere related to the custom log name (maybe set a custom name so its easier to find)

There is nothing i can think of other than not having auth to gcp that should stop the logs. The containers are long lived so issue people have where containers shutdown and prevent logs from being sent shouldn't apply.

Instead of using this library at all at all you might consider extending winston.transports.Console to decorate the stdout logs in a way that keeps logs associated with the correct service and has the data you want.

here is an issue folks run into once they find their second set of logs. 
https://github.com/googleapis/nodejs-logging-winston/issues/386
