### ISSUE TITLE
Error: `write after end` when handling SIGINT

### ISSUE THREAD

**Issue by jamesholcomb** [googleapis/nodejs-logging-winston#502]
#### Environment details

  - OS: MacOS
  - Node.js version: 10 LTS
  - npm version:
  - `@google-cloud/logging-winston` version: 3.0.6
  - `winston` 3.2.1

#### Steps to reproduce
Winston 3 now has a mechanism to wait for logs to flush described here: https://github.com/winstonjs/winston/blob/master/UPGRADE-3.0.md#winstonlogger

> winston.Logger.log and level-specific methods (.info, .error, etc) no longer accepts a callback. The vast majority of use cases for this feature was folks awaiting all logging to complete, not just a single logging message.

Since upgrading, I am unable to get the logs to flush before the process exits (via signal or normal termination).
```js
const winston = require("winston")
const { LoggingWinston } = require("@google-cloud/logging-winston")

const logger = winston.createLogger({
  exitOnError: false,
  level: "info",
  transports: [
    new winston.transports.Console({
      handleExceptions: false
    }),
    new LoggingWinston({
      keyfileName:
        "/Users/jamesholcomb/keys/2e645b0b8d27.json",
      projectId: "my-proj"
    })
  ]
})

logger.emitErrs = false

logger.info("started")

process.on("SIGINT", () => {
  logger.info("Ctrl-C pressed")
  logger.on("finish", () => process.exit(0))
  logger.end()
})

process.openStdin()
```
Output error:
```
{"message":"started","level":"info"}
^C{"message":"Ctrl-C pressed","level":"info"}
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (/Users/jamesholcomb/gcp-test/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:261:12)
    at DerivedLogger.Writable.write (/Users/jamesholcomb/gcp-test/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:305:21)
    at DerivedLogger.info (/Users/jamesholcomb/gcp-test/node_modules/winston/lib/winston/create-logger.js:81:14)
    at process.on (/Users/jamesholcomb/gcp-test/index.js:42:10)
    at process.emit (events.js:198:13)
Emitted 'error' event at:
    at errorOrDestroy (/Users/jamesholcomb/gcp-test/node_modules/winston/node_modules/readable-stream/lib/internal/streams/destroy.js:98:101)
    at writeAfterEnd (/Users/jamesholcomb/gcp-test/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:263:3)
    at DerivedLogger.Writable.write (/Users/jamesholcomb/gcp-test/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:305:21)
    [... lines matching original stack trace ...]
    at process.emit (events.js:198:13)
```
If I comment out the LoggingWinston transport setup, there is no error.

**Comment by jamesholcomb** [comment]
I played around with this to see if I could get past the error.  Changing  https://github.com/googleapis/nodejs-logging-winston/blob/8bc9aad593e47082b42fea8e4bfc34f605da9c40/src/index.ts#L182

to

```js
this.common.log(info[LEVEL] || level, message, metadata || {}, () => this.emit('finish');
```
works around it.

**Comment by bcoe** [comment]
@jamesholcomb thanks for the good reproduction 👍

**Comment by jamesholcomb** [comment]
Here's a workaround I'm using that does not require changing the lib:

```js
setTimeout(() => logger.end(), 1000)
```

**Comment by jamesholcomb** [comment]
Is there an internal path forward on this?  The workaround is not effective for task oriented processes that perform heavy logging then exit...it's impossible to know how long to delay.

**Comment by bcoe** [comment]
@jamesholcomb I think to address this what we would need to do would be to add a feature to `@google-cloud/logging` that tracks all of the logs that have been sent but not emitted yet.

Another workaround you might be able to use Node.js', `process._getActiveRequests()`/`process._getActiveHandles()` to introspect whether there are any requests still on the wire ... I'm not sure how this behaves with http2 however.

**Comment by RLRabinowitz** [comment]
How is this not a bug? The [suggested way](https://github.com/winstonjs/winston/blob/master/UPGRADE-3.0.md#winstonlogger) of flushing logs doesn't work in this basic reproducible environment

This also happens to us occasionally, and we couldn't use `setTimeout` on the `logger.end`, since we have no idea how long we'll have to wait here.

Is there any possible solution for this? In v2 I could have flushed the logs without ending by using the callback arg in `logger.info`, but we're using v3 so that's not possible anymore

**Comment by losalex** [comment]
@jamesholcomb and @RLRabinowitz , do you think that fix provided by @chrismaree helps?

**Comment by losalex** [comment]
@RLRabinowitz , sorry for late reply and thanks for shared workaround!
I am still checking with our team on possible solution and will get back to you.

**Comment by losalex** [comment]
After looking for this issue more, unfortunately I do not have a great solution for this problem without making some redesign - the removed callback support in `winson` library breaks the contract we have for `nodejs-logging` library APIs which are `async` and callback oriented (based on what I see there is no way to `await` on `winston` calls). One possible solution to this problem is to leverage [printing structured logging to STDOUT](https://github.com/googleapis/nodejs-logging-winston/pull/676) solution which could be used if you run in Google Cloud environment with Cloud Logging Agent enabled (or any cloud which has an ability to capture `process.stdout` data and send it to Cloud Logging). The other option is to bring back callback functionality in `winston`.  
I am open to any suggestions at this point - please let me know if you have any ideas/comments on this matter.

**Comment by RLRabinowitz** [comment]
Hey @losalex, gotta say that I'm not sure what other option would be available, other than bringing back callback functionality. 

We've already solved our issue internally with [this workaround](https://github.com/googleapis/nodejs-logging-winston/issues/502#issuecomment-1036003816) mentioned above, which is specific to the transports we use

My main issue with this personally right now is that the "breaking changes" part of the changelog is misleading. The [suggested way](https://github.com/winstonjs/winston/blob/master/UPGRADE-3.0.md#winstonlogger) of migrating to 3.0 is wrong, it should either mention `setTimeout` there, or say that the functionality is no longer available

**Comment by losalex** [comment]
Thanks @RLRabinowitz for your response - I agree that the migration was not properly addressed. I am not sure what exactly happened (this migration predates me), but I guess that `winston` change was introduced independently since it is not part of `googleapis` project. I believe the `winston` 3.0 migration was inevitable in order to be up to date with latest `winston` changes and the issue with `write after end` was discovered later due to `async` nature of [Log](https://github.com/googleapis/nodejs-logging/blob/7434d649a3ac0ecbf6299719403df35a2c1a833e/src/log.ts#L117).
I must admit that such migration in `winston` library supposed to be backward compatible for the sake of clients relying on such functionality - filed the [2095](https://github.com/winstonjs/winston/issues/2095) on `winston` to revive callback functionality. As of now, I do not see how we can solve this issue except of using [printing structured logging to STDOUT](https://github.com/googleapis/nodejs-logging-winston/pull/676) feature since current default solution is `async`/callback oriented. 
I am happy that you have a workaround as of now - thanks for sharing it since it could be leveraged by more users! I believe that for now we should add some explanation in `README` regarding this limitation.

**Comment by jamesholcomb** [comment]
I understand that updating the README can help explain the context of the bug, but this needs to remain open so that a proper fix can be implemented.  @bcoe suggested a path forward by tracking pending requests.

**Comment by losalex** [comment]
> I understand that updating the README can help explain the context of the bug, but this needs to remain open so that a proper fix can be implemented. @bcoe suggested a path forward by tracking pending requests.

Thanks for your comment @jamesholcomb - sorry, this issue was closed automatically by README change. Perhaps I should explain more on a reason why I think there is no good solution might be here. Tracking pending requests could address the issue only partially - correct me if I wrong, but some of the data still could be buffered on a transport level. Also worth mentioning that I do not see a `flush` on a `Writable` which could trigger all data to be written - let me know if you think there is a way to trigger data flush.
As I mentioned earlier, the base library [googleapis/nodejs-logging](https://github.com/googleapis/nodejs-logging) is designed to use callbacks as a tracking mechanism (since awaiting on every call could be problematic). We also have a solution for [printing structured logging to STDOUT](https://github.com/googleapis/nodejs-logging-winston/pull/676) as alternative which could be used with logging agents in a cloud. 
So based on said before, I believe the only way to fully address the issue is to return callback functionality to `Winston` library which is tracked by [2095](https://github.com/winstonjs/winston/issues/2095). This would be also a right step to maintain backward compatibility on a library which I believe should be a common practice for SDKs used by many users.
Please let me know what do you think about it. Feel free to reactivate a work item if you feel this could be somehow addressed by some fix in this library.

**Comment by elyobo** [comment]
@losalex it seems like winston implements its logger as a `Transform` stream and [pipes to its transports](https://github.com/winstonjs/winston/blob/7937f337dac50b4f134bbfa88f72bdd313ad0af5/lib/winston/logger.js#L364), [delaying the finish event](https://nodejs.org/api/stream.html#writable_finalcallback) (according to the [docs on `_final`](https://nodejs.org/api/stream.html#writable_finalcallback)) until the transports are all finished.

It looks like the `nodejs-logging-winston` transport is a `Transform` stream as well ([via `winston-transform`](https://github.com/googleapis/nodejs-logging-winston/blob/main/src/index.ts#L15)), so it seems like if your transport can keep track of its own state, then perhaps all it needs to do is implement its own `_final` that defers things until it has finished sending the logs and then winston will behave correctly?
