### ISSUE TITLE
Setting `logName` results in duplicate logs

### ISSUE THREAD

**Issue by rubenvereecken** [googleapis/nodejs-logging-winston#528]
#### Environment details
  - Node.js version: v12.16.2
  - `@google-cloud/logging-winston` version: 3.0.6 (I'll update though)

#### Steps to reproduce
~~It looks like when I set `logName` in the LoggingWinston transport options, I get duplicate logs. One for `winston_log` which appears to be the default and one for my specified `logName` which in this case is `production`. Is this intended behaviour?~~

It looks like LoggingWinston is giving me duplicate logs. More of a nuisance than anything really, but I wonder why.

```
import {LoggingWinston} from '@google-cloud/logging-winston';

const logger = winston.createLogger({
	transports: [
		new LoggingWinston({
			level: 'debug',
		}),
	]
});

logger.info('This is a log message')
```

Without a filter, the following shows up:
![image](https://user-images.githubusercontent.com/5216553/88271183-b75ee400-ccce-11ea-80ce-49a5b52703a7.png)

**Comment by vorotech** [comment]
hi @rubenvereecken 
have faced the same issue and find in code why it happens (worked for me)

In my case I do setup logger options and createLogger using winston, my logger options already include `LoggingWinston` transport:

```typescript
import { createLogger } from 'winston'
import { express } from '@google-cloud/logging-winston';

const loggingOptions = {
        level: 'info',
        transports: [
            new transports.Console(),
            new LoggingWinston()
        ]
    }

const logger = createLogger(loggerOptions)

const app = ... // setup express app with NestJS and use logger as a main one

// create middleware of out logger to log to StackDrive the requests
const loggingMiddleware = await express.makeMiddleware(logger);   // <-- this is the root cause, see below
app.use(loggingMiddleware);
```

If you take a look at the source code the transport (`LoggingWinston`) has been initialized again, because it wasn't supplied as an argument while converting the Winston logger to middleware.

https://github.com/googleapis/nodejs-logging-winston/blob/4abe70560592e83f1326f210aaa4d10669bfdd7a/src/middleware/express.ts#L45-L53

In my case, the fix was to export the same **transport** I setup early for app logger.

```
import { googleTransport } from '../my-logger-options'

const loggingMiddleware = await express.makeMiddleware(logger, googleTransport); 
```

**Comment by laljikanjareeya** [comment]
@rubenvereecken I tried with above given snippet and mentioned version, but I could not reproduce it.

@vorotech In your case If you could see below in middleware if `optionsOrTransport` is not instance of `LoggingWinston` than the new instance will be created, otherwise it use the same instance.

https://github.com/googleapis/nodejs-logging-winston/blob/4abe70560592e83f1326f210aaa4d10669bfdd7a/src/middleware/express.ts#L45-L53

**Comment by laljikanjareeya** [comment]
@rubenvereecken where you able to reproduce the issue?

**Comment by kyle-mccarthy** [comment]
@laljikanjareeya I just ran into this problem as well. I don't instantiate my logger at the same time that I bind the middleware so  I had to make some changes to keep the instance in scope. 

Perhaps it would be possible to look for the `LogginWinston` transport on the logger and create it if it doesn't exist? I think it would be possible with:

```
const instance = logger.transports.find(t => t instanceof LoggingWinston);
```

**Comment by nicoleczhu** [comment]
Adopted @kyle-mccarthy 's solution
