### ISSUE TITLE
Feature req: allow use in front end in browser

### ISSUE THREAD

**Issue by garyo** [googleapis/nodejs-logging-winston#537]
I know this is "nodejs-logging-winston" but it would be great if there were a way to send front-end logs, especially via Winston, to Stackdriver.

**Comment by losalex** [comment]
Thanks @garyo for opening the PR!
Can you please elaborate a bit more regarding sending front end logs to Stackdriver? For example, which application/framework you use, where your app is running (e.g. browser?), is your app has backend servers?

**Comment by garyo** [comment]
In my case I'm using Vue/Vuetify and Google Firebase. App (app.bioviz-studio.com, check it out) is running in the browser, and has Google Cloud backend servers. It would be great to capture front-end logs (warnings, errors, significant events, etc.) into Google's stackdriver.

**Comment by losalex** [comment]
Thanks @garyo for clarifications and sorry for late response! 
I believe that it would be great to see nodejs-logging-winston running on client side fully integrated with Google Cloud Logging backend, but unfortunately as of now we do not have plans to support it. I also did some fast checks and I must admit it is not clear if `winston` library supported fully to run in browser - there is a thread mentioned [here](https://github.com/winstonjs/winston/issues/287), but it is not clear if solutions mentioned work.
As for browser side logging, we have the experimental library [stackdriver-errors-js](https://github.com/GoogleCloudPlatform/stackdriver-errors-js) which provides an ability to integrate directly with [Google Cloud Error Reporting](https://cloud.google.com/error-reporting/), so it could be used at least to report errors.
I am not sure how far you went with your research, but I wonder if you were able to try to run [winston](https://github.com/winstonjs/winston) in browser as suggested in [#287](https://github.com/winstonjs/winston/issues/287)? Since if that is possible, perhaps you could use `winston` library with a custom transport which could expose error reporting abilities by utilizing [stackdriver-errors-js](https://github.com/GoogleCloudPlatform/stackdriver-errors-js) at least.
Please let me know what do you think about it or if there is anything else I can help with.
