### ISSUE TITLE
Include async call to close/flush LoggingWinston to use in Cloud Functions

### ISSUE THREAD

**Issue by dan-sproutward** [googleapis/nodejs-logging-winston#598]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
Logging is dropped if a Cloud Function shuts down before LoggingWinston flushes.
 **Describe the solution you'd like**
Asynchronous call that can be used to wait for LoggingWinston to flush before exiting function processing event(thread?).
 **Describe alternatives you've considered**
Created a Promise that calls close() and end() and listens for finish before returning. This is not reliable and logging is still dropped.
 **Additional context**
It is not clear to me how to flush LoggingWinston successfully. Calling close and end was a guess to force flush before exiting a function. This is not reliable.

**Comment by SurferJeffAtGoogle** [comment]
@dan-sproutward  did chrismaree's pull request fix this issue?

**Comment by dan-sproutward** [comment]
@SurferJeffAtGoogle just saw your comment. my request was based on observations that we seemed to be dropping logging. I will need to revisit this and that won't happen for a little bit - <excuses>I am in the weeds and had moved on from the codebase using this functionality</excuses>. However, now that I know, I will get this back on my plate to see if it is making a difference. Thanks for the heads up.

**Comment by losalex** [comment]
Thanks @dan-sproutward for raising this issue. 
I wonder if you tried the suggestion explained in [awaiting-logs-to-be-written-in-winston](https://github.com/winstonjs/winston#awaiting-logs-to-be-written-in-winston) and if yes, did it improved anything?

**Comment by losalex** [comment]
@dan-sproutward , another way to resolve this issue is to expose the [logSync](https://cloud.google.com/nodejs/docs/reference/logging/latest/logging/logsync) class as additional winston transport in this library. `logSync` is recommended for usage in serverless environment since by default all logging output goes to `stdout` which is picked by the agent running on every node, so logging calls should not delay process significantly. Can you please let me know if this solution would be acceptable? Also, can you please share which parameters you use in [LoggingOptions](https://github.com/googleapis/nodejs-logging-winston/blob/d1cad8d45a379fc3f410545e58ec5323217da1e4/src/index.ts#L42) to create a [LoggingWinston](https://github.com/googleapis/nodejs-logging-winston/blob/d1cad8d45a379fc3f410545e58ec5323217da1e4/src/index.ts#L173)?

**Comment by losalex** [comment]
@dan-sproutward , I believe that [676](https://github.com/googleapis/nodejs-logging-winston/pull/676) provides a good alternative solution for this issue - please let me know if that helps. Closing this issue for now - feel free to reopen or comment if you have any issues.
