### ISSUE TITLE
Emit errors instead of throwing exceptions where possible

### ISSUE THREAD

**Issue by minherz** [googleapis/nodejs-logging-winston#627]
#### Environment details

  - npm version: 16.4
  - `@google-cloud/logging-winston` version: 4.1.1

#### Steps to reproduce

  1. Follow example shown in #623
  2. Provide invalid (non-existent) project id

#### Observed result

The execution throws exception which lead to the application crash. The only way to handle it is to process unhanded exceptions in the process level.

```nodejs
process.on('uncaughtException', function(err) {
  
    // Handle the error safely
    console.log(err)
})
```

#### Expected result

The error event is emitted at the level of the LoggingWInston object.

**Comment by minherz** [comment]
We need to introduce a more intelligent error handling for all API calls to avoid crashing application in case an API call returns error. The errors should be reported on the level of the Logging instance. Dependent libraries such as logging-winston should propagate these errors to the level of their instance (e.g. LoggingWinston for logging-winston).

**Comment by daniel-quantica** [comment]
Alternative steps to reproduce:

Turn off your application's internet connection, wait 10min for google-gax to issue a timeout and watch the whole application crash.

We use this library in an application that is perfectly fine running without internet. It's designed to work in the local network. This night we lost internet connectivity and 10min later all app instances crashed because the logger failed.

A different way to handle these errors would be highly appreciated :)
