### ISSUE TITLE
Lost log message when using `httpRequest` in metadata

### ISSUE THREAD

**Issue by TakeshiDaveau** [googleapis/nodejs-logging-winston#663]
#### Environment details

  - OS: MacOS or Google Cloud Platform GKE
  - Node.js version: 14.7.0
  - npm version: 
  - `@google-cloud/logging-winston` version: 4.1.1
  -  `@google-cloud/logging` version: 9.6.7
  - `@nestjs/core` version: 7.0.0
  - `winston` version: 3.4.0

#### Steps to reproduce

  1. Configure winston to use the transport WinstonLogging
  2. Create 3 logs messages 
   
```
logger.info('First message')
logger.info('Request', {
        httpRequest: {
          requestMethod: request.method,
          requestUrl: request.url,
          status: response.statusCode,
          latency: duration,
          protocol: request.protocol,
        }
})
logger.info('Third message')
```
  3. The first log i available in Log Explorer, the second and the third are not, without any error message.

After some investigation I isolate the problem, which is the method `writeLogEntries`. When there is one log message with `httpRequest` it doesn't do anything: no promise resolution, no promise rejection. 

```
    async write(entry, opts) {
        const options = opts ? opts : {};
        // Extract projectId & resource from Logging - inject & memoize if not.
        await this.logging.setProjectId();
        this.formattedName_ = log_common_1.formatLogName(this.logging.projectId, this.name);
        const resource = await this.getOrSetResource(options);
        // Extract & format additional context from individual entries.
        const decoratedEntries = this.decorateEntries(arrify(entry));
        this.truncateEntries(decoratedEntries);
        // Clobber `labels` and `resource` fields with WriteOptions from the user.
        const reqOpts = extend({
            logName: this.formattedName_,
            entries: decoratedEntries,
            resource,
        }, options);
        delete reqOpts.gaxOptions;
        return this.logging.loggingService.writeLogEntries(reqOpts, options.gaxOptions);
    }
```
This piece of code comes from  @google-cloud/logging` version: 9.6.7

**Comment by EronWright** [comment]
Could you try closing the logger to flush entries?   Here's how to do that with a promise:
```
await new Promise((resolve) => {
        logger.once('finish', () => resolve(null));
        logger.end();
    });
```

**Comment by losalex** [comment]
Thanks @TakeshiDaveau for opening this issue! 
The suggestions provided by @EronWright is the good way to close the logger and hence flush it. There is one caveat though - there is a possibility to encounter '**Error: write after end**' as described in [#502](https://github.com/googleapis/nodejs-logging-winston/issues/502). This error appeared after `winston` v3 upgrade which removed callback support on all `winston` APIs - the callback was used to track writes since base library [googleapis/nodejs-logging](https://github.com/googleapis/nodejs-logging) is designed to use callbacks instead of awaiting for every call to complete. Possible workaround to avoid '**Error: write after end**' is to make a call to `logger.end()` after timeout, e.g:

```js
setTimeout(() => logger.end(), 5000);
```

Please let me know if I can help with anything else.

**Comment by losalex** [comment]
Closing this issue for now - feel free to reactivate or ask more questions if needed.
