### ISSUE TITLE
how to get kubernetes information attached to log (google-cloud/logging-winston)

### ISSUE THREAD

**Issue by hitzam-wartek** [googleapis/nodejs-logging-winston#783]
Hi,

I just started to use  (google-cloud/logging-winston) on my nodeJs service. I'm expecting to get full information on resource object on the log like this as on my dotnet service:
```
resource: {
	labels: {
		cluster_name: "staging-2"
		container_name: "service-api"
		location: "asia-southeast2"
		namespace_name: "be-tribe"
		pod_name: "service-api-staging-6798e57f9b-4xcmt"
		project_id: "mydotnetservice-staging"
	}
	type: "k8s_container"
}
severity: "WARNING"
timestamp: "2023-02-08T08:17:54.456124700Z"
}
```

I have tried this on my code (following [this example](https://github.com/googleapis/nodejs-logging-winston/issues/285#issuecomment-522460175)):
```
const googleLoggingWinston = new LoggingWinston({
    serviceContext: {
        service: process.env.APPLICATION_NAME,
        version: 'staging',
    },
});
```
and these that all I got on the log:
```
resource: {
	labels: {
		project_id: "mynodeservice-staging"
	}
	type: "global"
}
severity: "INFO"
timestamp: "2023-02-08T08:33:27.161999940Z"
}
```

Anyone experienced the same issue?

**Comment by cindy-peng** [comment]
Hi @hitzam-wartek , could you please share the details how you create the log, configure the logging options and how you log the information?

**Comment by cindy-peng** [comment]
Hi @hitzam-wartek, we automatically detect resource type and add resource info by detecting resource types from environment variables:
https://github.com/googleapis/nodejs-logging/blob/5b57cdb9fc36f898e12db0afe456e63e9efcf56c/src/utils/metadata.ts#L139

https://github.com/googleapis/nodejs-logging/blob/5b57cdb9fc36f898e12db0afe456e63e9efcf56c/src/utils/metadata.ts#L187

Please check if your environment variables are set properly. I am closing this issue for now since we don't have a recent repro. Feel free to reopen it if you are still running into this. Thanks!
